# Relevant Documentation:
# - [M5Stack AtomS3 Lite, ESPHome](https://devices.esphome.io/devices/m5stack-atoms3-lite/)
# - [i2c for extra sensor](https://github.com/fonske/Mitsubishi_procon/blob/main/esphome/boards/board-m5stack-atoms3-lite.yaml)

esphome:
  name: njord-air-quality-sensor
  friendly_name: "Njord | Air Quality Sensor"
        
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

logger:
  level: DEBUG

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: "1bc031bd88c44a0bb95509baa991a059"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.0.59
    gateway: 192.168.0.1
    subnet: 255.255.255.0
  ap:
    ssid: "Njord-Air-Quality-Sensor"
    password: "Kxa9pQwTfPV3"

captive_portal:

web_server:
  port: 80

i2c:
  - id: i2c_grove
    sda: GPIO2
    scl: GPIO1
    frequency: 100kHz
    scan: true

sensor:
  - platform: scd4x
    i2c_id: i2c_grove
    address: 0x62
    automatic_self_calibration: false
    update_interval: 10s
    co2:
      name: "CO2"
      id: co2
      accuracy_decimals: 1
    temperature:
      name: "Temperature"
      id: temperature
      accuracy_decimals: 2
    humidity:
      name: "Humidity"
      id: humidity
      accuracy_decimals: 1
  - platform: template 
    name: "VPD" 
    icon: "mdi:gauge"
    id: vpd
    lambda: |-
        return (((100 - id(humidity).state) / 100.0) * (0.6108 * exp((17.27 * id(temperature).state) / (id(temperature).state + 237.3))));
  - platform: uptime
    name: "Uptime"